export { renderHomePage } from './home'
export { renderAboutPage } from './about'
export { renderServicesPage } from './services'
export { renderPracticeAreasPage } from './practice-areas'
export { renderArticlesPage } from './articles'
export { renderContactPage } from './contact'
